* Nov, 30, 2020: Discussion with Dr. Dib-Hajj
** spoke with Dr. Dib-Hajj and his lab regarding modelling.
powerpoint is located in research_supplement/meeting_11_30_20.pdf
**** notes:
    RMP for cell shows large variability, Choi, Waxman 2011 -50 mV to -70 mV with NaV 1.7 
    Nociceptive C fibres only fire at very low frequencies -- show signal attenuation beyond these very low frequencies
    stim patterns, evaluation of the peripheral nerve with short current pulses vs. evaluation of the soma with slow depolarizations
        Some newer information Vasylyev, Waxman 2011 on electrogenesis at the peripheral nerve ending: https://paperpile.com/app/p/8cd7642b-66b9-0295-8f92-698ff083ae04
    Comparison of NaV, Sheets, Waxman 2007, Choi, Waxman 2011 and Mange, Machanda 2018
*****   concern over Choi, Waxman 2011 regarding utilization of NaV 1.8.
            Briefly:
            Nav1.8 sodium current.
            The Nav1.8 sodium current (INav1.8) was best fit with a HH model that employed <<1>> only one activation gate: INav1.8 = gNav1.8 * m * h * (V − ENa), where gNav1.8 is the Nav1.8 sodium conductance and m and h are dimensionless activation and inactivation variables that vary between 0 and 1. Based on previous reports (Herzog et al. 2001; Sheets et al. 2007), we defined the following equations for Nav1.8 m and h <<1>>: m = m + [1 − exp(−dt/taum)] * (minf − m), h = h + [1 − exp(−dt/tauh)] * (hinf − h), alpham = 2.85 − (2.839)/{1 + exp[(v − 1.159)/13.95]}; betam = (7.6205)/{1 + exp[(v + 46.463)/8.8289]}; taum = 1/(alpham + betam); minf = alpham/(alpham + betam); tauh = (1.218 + 42.043 * exp{−[(v + 38.1) ∧ 2]/(2 * 15.19 ∧ 2)}); hinf = 1/{1 + exp[(v + 32.2)/4]}. The peak current of 25 nA was modeled by setting the peak value gNav1.8 to 0.026 S/cm2, which was chosen to match experimental values (Choi et al. 2007; Cummins and Waxman 1997).

            There is confusion over the use of the modelling with only one m activation gate, the "INav1.8 = gNav1.8 * m * h * (V − ENa)" equation, as the equations for rate/ tau, inf equations:

            alpha_m = 2.85-(2.839)/(1+exp((v-1.159)/13.95))
            beta_m = (7.6205)/(1+exp((v+46.463)/8.8289))

            tau_h = (1.218+42.043*exp(-((v+38.1)^2)/(2*15.19^2)))
            inf_h = (1)/(1 + exp((v+32.2)/4))

            all come from Sheets et al. 2007, though in this paper, the formula for current does not use a single m activation gate to describe activation but instead is:

            ina = gnabar * m^3 * h * (v-ena)

            The one activation gate is seeming taken from Herzog et al. 2001, is describing a TTX-RP (i.e. NaV 1.9) current, which has a significantly different set of equations

            alpham  = 1.032/{1 + exp[(υ + 6.99)/−14.87115]}
            betam   = 5.79/{1 + exp[(υ + 130.4)/22.9]}

            alphah  = 0.06435/{1 + exp[(υ + 73.26415)/3.71928]}
            betah   = 0.13496/{1 + exp[(υ + 10.27853)/(−9.09334)]}
* Dec, 13, 2020: gatherData does not gatherData into the master node
** from multiprocessor sim
Gathering data...
  Done; gather time = 0.29 s.

Analyzing...
  Cells: 126
  Connections: 0 (0.00 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 0.0 s; 4 workers
  Run time: 0.85 s
hello from the master node!
analyzing 32 cells
** will need to analyze from pkl data most likely, as json files are very bloated.


